### ISSUE TITLE
Latest version of beangle-jakarta-dwr is not Spring 6 compliant

### ISSUE THREAD

**Issue by suzieq26** [beangle/jakarta#1]
Hi, first of all thanks for creating the jakarta EE version of this jar! I noticed that the latest published version (3.0.4-RELEASE) is still not Spring 6 compliant. Are there any plans to publish Spring 6.x complaint version anytime soon?

**Comment by jbisotti** [comment]
I'm curious, what is not Spring 6.x compliant?

**Comment by DigitalInd92** [comment]
Hi @jbisotti , yes this version is not compatible with Spring 6 I am getting the below exceptions:


Caused by: org.springframework.beans. Fatal BeanException: Unresolvable class definition for NamespaceHandler class
[org.directwebremoting.spring.DwrSpringNamespaceHandler) for namespace [http://www.directwebremoting.org/schema/spring-dwr]
at org.springframework.beans.factory.xml.DefaultNamespaceHandler Resolver.resolve(DefaultNamespaceHandler Resolver.java:144)
at org.springframework.beans.factory.xml. BeanDefinitionParserDelegate.parseCustomElement(BeanDefinition ParserDelegate.java:1386)
at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinition ParserDelegate.java:1371)
at org.springframework.beans.factory.xml.DefaultBeanDefinition DocumentReader.parseBeanDefinitions (DefaultBeanDefinition DocumentReader.java:179)
at org.springframework.beans.factory.xml.DefaultBeanDefinition DocumentReader.doRegister BeanDefinitions (DefaultBeanDefinition DocumentReader.java:150)
at org.springframework.beans.factory.xml.DefaultBeanDefinition DocumentReader.register BeanDefinitions (Default BeanDefinition DocumentReader.java:96)
at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.register BeanDefinitions(XmlBeanDefinitionReader.java:520)
at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:400)
59 common frames omitted


Caused by: java.lang.NoSuchMethodError: 'void org.springframework.util.Assert.notNull (java.lang.Object)'
at org.directwebremoting.spring.namespace.ConfigurationParser.<init>(ConfigurationParser.java:55)
at org.directwebremoting.spring.DwrSpringNamespaceHandler.init(DwrSpringNamespaceHandler.java:53)
at org.springframework.beans.factory.xml.DefaultNamespaceHandler Resolver.resolve(DefaultNamespaceHandlerResolver.java:135)

**Comment by duantihua** [comment]
I'm very sorry, but since DWR has been in disrepair for a long time and Spring 7 is currently thriving, I think it's time to switch to another technology route. Perhaps you could clone it and make some targeted fixes.
